version: '3'

services:

  quepasa:
    image: quepasa
    container_name: "codeleaks-quepasa"
    env_file: .env
    ports:
      - 31000:31000
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    volumes:
      - ../src:/opt/quepasa
    restart: always
    stdin_open: true
    tty: true
    networks:
      - quepasa_network
    extra_hosts:
      - "host.docker.internal:host-gateway"
  
networks:
  quepasa_network:
